exports.ROLES = {
  ADMIN: 'ADMIN',
  CONSUMER: 'CONSUMER',
};

exports.PRIORITIES = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

exports.STATUS_CODES = {
  NODE_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  DELETED: 'DELETED',
  NAME_INVALID: 'NAME_INVALID',
  USERNAME_INVALID: 'USERNAME_INVALID',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
  USERNAME_OR_PASSWORD_INCORRECT: 'USERNAME_OR_PASSWORD_INCORRECT',
  GROUP_NAME_INVALID: 'GROUP_NAME_INVALID',
  GROUP_DESCRIPTION_INVALID: 'GROUP_DESCRIPTION_INVALID',
  GROUP_PRIORY_INVALID: 'GROUP_PRIORY_INVALID',
  TASK_NAME_INVALID: 'TASK_NAME_INVALID',
  PRIORITY: 'PRIORITY_INVALID',
};

exports.TOKEN_TYPES = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
};

exports.SORTS = {
  ASC: 'asc',
  DESC: 'desc',
};
