version: '3.9'

networks:
  app-net:

services:
  api:
    image: node:16.10.0-alpine
    container_name: api
    user: 1000:100
    working_dir: /app
    command: yarn dev --l
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-net
